default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ny_museums
  username: postgres
  host: 10.0.0.17
  port: 5432
  password: docker
  encoding: unicode 
